### ISSUE TITLE
nx-vite:serve is not working with npm

### ISSUE THREAD

**Issue by rvetere** [sevenwestmedia-labs/nx-plugins#37]
A freshly created project with `nx-vite:react` is not working with `nx serve` command.. following error is coming from npm package manager which i still have from the default workspace settings. Do i need to use a different package manager?

<img width="734" alt="Screenshot 2021-07-23 at 19 10 49" src="https://user-images.githubusercontent.com/1505976/126817706-79d22e60-989c-44d5-bcf9-c1f5c140cacb.png">

**Comment by RickieWoo** [comment]
Hi, I hava the same question, any solution here?

**Comment by JakeGinnivan** [comment]
Sorry about this! We were using yarn in repos with this plugin. Thanks for the report.

**Comment by JakeGinnivan** [comment]
Fix published in 0.4.2
