### ISSUE TITLE
devkit_1.writeJson is not a function

### ISSUE THREAD

**Issue by KeKs0r** [sevenwestmedia-labs/nx-plugins#39]
Hi,

I really like what you are up to here, and it can potentially solve all my pain points with NX. So really excited to play around with it.

When trying to run the migrate command on our current NX codebase, I am receiving the following error:
```
devkit_1.writeJson is not a function
```

Is this due to my NX version?

**Comment by JakeGinnivan** [comment]
It could be due to the typescript config, possibly need to set `esModuleInterop` @KeKs0r

**Comment by KeKs0r** [comment]
I am not sure how, but I ended up fixing it by upgrading all the way through to NX 12. I also had issues with missing angular/devkit in my project.

**Comment by JakeGinnivan** [comment]
Ah right, yeah I've only tested this on NX12. Thanks for following up!
