### ISSUE TITLE
esbuild fails to start with no package.json in an app

### ISSUE THREAD

**Issue by kesne** [sevenwestmedia-labs/nx-plugins#43]
It looks like the `readJson` function throws if the `package.json` is not in an app. The docs seem to indicate that this should not be a fatal case, and it should instead just fallback to the root `package.json`.

**Comment by JakeGinnivan** [comment]
This is fixed in https://github.com/sevenwestmedia-labs/nx-plugins/releases/tag/%40wanews%2Fnx-typescript-project-references%400.13.0

Thanks for the report
