### ISSUE TITLE
wrong tsconfig.json and fail when run serve

### ISSUE THREAD

**Issue by tsanyqudsi** [sevenwestmedia-labs/nx-plugins#45]
Hi,

I'm new in using NX, so maybe i miss some steps here.

Basically i finally able to use your nx-vite plugin and finally created the folder into my workspace successfully. However, i have troubles in few areas :

1. tsconfig.json

In noticed in your repo that there's `tsconfig.setting.json` whereas in my newly created nx workspace there's only `tsconfig.base.json` so i need to change it manually.

i used  `--preset=empty` for creating the workspace.

the changes i need to make to tsconfig.json is : 

from 
```
{
  "extends": "../../tsconfig.settings.json",
  "compilerOptions": {
    "outDir": "./out-tsc",
    "rootDir": "./src",
    "types": ["jest", "node"]
  },
  "include": ["src/**/*.ts", "src/**/*.tsx"]
}
```
to

```
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "./dist",
    "jsx": "react-jsx",
    "types": ["jest", "node"]
  },
  "include": ["src"]
}
```
2. `nx run <my app>:serve`

when i run serve, i got an error.

```
Command failed with exit code 243: npx vite <my app path>--open
Error: Command failed with exit code 243: npx vite <my app path> --open
    at makeError (/<my app path>/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/<my app path>node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

can you show me where did i go wrong or is it actually a bug ?

**Comment by JakeGinnivan** [comment]
Hey @tsanyqudsi 

This isn't explained very well, but we rely on the setup from https://github.com/sevenwestmedia-labs/nx-plugins/tree/main/libs/typescript-project-references

A bit of background on our approach is https://github.com/sevenwestmedia-labs/nx-plugins/tree/main/libs/typescript-project-references

I will make the Vite plugin add that file if it doesn't exist though to make it easier to use the plugin

**Comment by tsanyqudsi** [comment]
@JakeGinnivan i don't use nx anymore since the problem really made me and my team can't do anything. We tried a lot of things and since early of september we decided that more than a week is enough to try new things :)
