### ISSUE TITLE
Package "@wanews/nx-vite" was found but does not support schematics.

### ISSUE THREAD

**Issue by anoop-gupt** [sevenwestmedia-labs/nx-plugins#47]
While running 
npx nx generate @wanews/nx-vite:react test

getting issue - Package "@wanews/nx-vite" was found but does not support schematics.

Any  @pointer?? @JakeGinnivan

**Comment by JakeGinnivan** [comment]
What version of NX are you using @anoop-gupt ?

`nx generate @wanews/nx-vite:react --name=test` seems to work with 12.9

**Comment by anoop-gupt** [comment]
Thanks @JakeGinnivan  I am using older version 10.3.3

**Comment by JakeGinnivan** [comment]
Ah yep, I think it was v11 or so when they changed from schematics to generators

**Comment by anoop-gupt** [comment]
Thanks, I will update the version and check.
