### ISSUE TITLE
project_graph_1.createProjectGraphAsync is not a function

### ISSUE THREAD

**Issue by avkonst** [sevenwestmedia-labs/nx-plugins#58]
I hoped your tool could help to enable support for project references in nx. I tried it. It emits the following error:

```
❯ npx nx generate @wanews/nx-typescript-project-references:migrate
project_graph_1.createProjectGraphAsync is not a function
```

**Comment by JakeGinnivan** [comment]
What version of NX are you running? I've only tested on v12/13
