### ISSUE TITLE
[nx-esbuild] nx 13.10.0+ tree path changed

### ISSUE THREAD

**Issue by hoonoh** [sevenwestmedia-labs/nx-plugins#69]
With `@wanews/nx-esbuild@0.22.0` + `nx@13.10.0`, following error occurs:
```
Cannot find module 'nx/src/shared/tree'
Require stack:
- node_modules/@wanews/nx-esbuild/src/executors/build/executor.js
- node_modules/nx/src/config/workspaces.js
- node_modules/nx/src/command-line/run.js
- node_modules/nx/bin/run-executor.js
```

https://github.com/sevenwestmedia-labs/nx-plugins/blob/5c9d8bbd78f61fa85a4b7632c090297a74e113ad/libs/nx-esbuild/src/executors/build/executor.ts#L3

Looks like path to tree has been refactored from `packages/nx/src/shared/tree.ts` to `packages/nx/src/config/tree.ts`

Related PR:
[cleanup(core): create more meaningful file structure in nx package #9621](https://github.com/nrwl/nx/pull/9621)
https://github.com/nrwl/nx/pull/9621/files#diff-ecb44f754a1e1420adb824a5bbd14c752c5c3ce076b49e17ed51450ff8c7b3e4

**Comment by JakeGinnivan** [comment]
I would love to know if there is a better way to work with the FsTree in executors so it isn't a deep import to prevent this kind of break. I will publish a fix for ☝️
