### ISSUE TITLE
[nx-pulumi] - nx-pulumi:restore-config command now restores file contents as an object

### ISSUE THREAD

**Issue by Hemesh-Unka** [sevenwestmedia-labs/nx-plugins#82]
Hello,

Thanks once again for maintaining this plugin! Using the latest version trying to restore my config, i get only `[object Object]` in my newly created yaml file.

I believe it is related to the below when the s3 dependency was swapped over:
https://github.com/aws/aws-sdk-js-v3/issues/1877

Not sure if this affects anything else in the repo.

Cheers!

**Comment by JakeGinnivan** [comment]
Hey @Hemesh-Unka thanks for the link to that thread. How annoying. 

I'm releasing https://github.com/sevenwestmedia-labs/nx-plugins/pull/85 now which should fix the issue. Let me know.
